### ISSUE TITLE
Flags created via IaC arent available to Identities

### ISSUE THREAD

**Issue by chriss-amd** [Flagsmith/terraform-provider-flagsmith#66]
Hi There

Sorry to raise another issue, we noticed that there was a fix for the importing of existing flags, so have been actively using IaC for Flagsmith, however have identified another issue. When flags are created via terraform/IaC they arent available straight away for users/identities, unless we actually toggle them on/off at the Environment level in the UI. Just to clarify this does seem to be only effect flags created via terraform/IaC other means of creating flags dont exhibit this behaviour. 

To give an bit of an example. We have the below IaC code to create a flag.

```
resource "flagsmith_feature" "timeline_content_block" {
  feature_name    = "timeline_content_block"
  project_uuid    = var.project_uuid
  description     = ""
  type            = "STANDARD"
  default_enabled = false
  lifecycle {
    ignore_changes = [
      owners
    ]
  }
}

```

When we run our terraform plan/apply commands does create the flag in Flagsmith like so

![image](https://user-images.githubusercontent.com/83659417/227957726-638a3342-a753-440f-9297-8b1cfd927c3d.png)

However when using the SDK for C# to get a list of flags for the identity. We dont get that flag back, unless we toggle it on/off for the environment, has to be at the environment level, trying to toggle it on/off at the identity level doesnt have any effect, essentially when a request to get that flag happens it resets the flag for that identity to default status.

An example of our C# code

```
FlagsmithClient _client = new FlagsmithClient("serverSideKey");
var flags = await _client.GetIdentityFlags("identifier");  //<-- Flags will not contain the additional flag created until toggling for the environment
var flag = await flags.GetFlag("timeline_content_block");

```

Happy to provide any more details if required.

**Comment by gagantrivedi** [comment]
I can't reproduce this can you provide some more information please:

1. Are you self-hosted or on SaaS
2. Do you have  `hide disabled flags` on? 
3. Can you check if the flags are returned using curl? Here is a sample request that you can use

```
curl --location --request GET 'https://edge.api.flagsmith.com/api/v1/identities/?identifier=<some-user-identifier>' \
--header 'X-Environment-Key: <Your key>' \

```
4. What version of terraform provider are you using
5. Is that the whole terraform configuration for the feature? Or are you creating any environment/segment override?

**Comment by chriss-amd** [comment]
Hi

Happy to provide more information. Please find answers to your question below. 

1. We are currently using SaaS.
2. We currently have the Hide disabled flags from SDKs set to Off
3. The flag is not returns as part of the response from the curl command
![image](https://user-images.githubusercontent.com/83659417/228178566-5633597a-25ef-4edd-9ba6-82b3991273fc.png)

```
{"flags": [
{"feature": {"id": 36481, "name": "test_feature", "type": "STANDARD"}, "enabled": false, "feature_state_value": null}, 
{"feature": {"id": 36483, "name": "exhibitions_creation", "type": "STANDARD"}, "enabled": false, "feature_state_value": null}, 
{"feature": {"id": 37177, "name": "my_test_feature", "type": "STANDARD"}, "enabled": false, "feature_state_value": null}, 
{"feature": {"id": 37425, "name": "favicon_customization", "type": "STANDARD"}, "enabled": false, "feature_state_value": ""}, 
{"feature": {"id": 37643, "name": "admin_user_limit", "type": "STANDARD"}, "enabled": true, "feature_state_value": 5}, 
{"feature": {"id": 41278, "name": "timeline_content_block", "type": "STANDARD"}, "enabled": true, "feature_state_value": null}], "traits": [{"trait_key": "package", "trait_value": "essential"}]}

```
4. Below is our versions we using

```
terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.54"
    }

    flagsmith = {
      source  = "Flagsmith/flagsmith"
      version = "0.4.1"
    }
  }
}
```

5. Pretty much, we have a main file with all the flags in this same format. There is no segments being created via IaC at the moment.

**Comment by gagantrivedi** [comment]
@chriss-amd I can't find a flag named `testing_flag_via_iac` in your project.
PS: can you ping us using the chat widget on our website please, (just to reduce the friction)

**Comment by gagantrivedi** [comment]
This is caused by race condition, fixed here: https://github.com/Flagsmith/flagsmith/pull/2081

**Comment by gagantrivedi** [comment]
Released here: https://github.com/Flagsmith/flagsmith/releases/tag/v2.49.1
