### ISSUE TITLE
flagsmith_feature does not manage feature tags

### ISSUE THREAD

**Issue by strugee** [Flagsmith/terraform-provider-flagsmith#67]
STR:

1. Create a new feature in Terraform and run `terraform apply`
2. Log into Flagsmith and go to the new feature's settings
3. Add a tag
4. Run `terraform plan` and notice that no diff is detected

**Comment by matthewelwell** [comment]
Thanks @strugee, we will take a look into this and get back to you.

**Comment by yuhuyoyo** [comment]
related feature request, can we add tag as a schema?

**Comment by gagantrivedi** [comment]
@yuhuyoyo  Yeah, We will pick it up next week
