### ISSUE TITLE
Can not pass variable value to string_value, integer_value or boolean_value in flagsmith_feature_state

### ISSUE THREAD

**Issue by hungvodcm** [Flagsmith/terraform-provider-flagsmith#76]
Hi All, 
I'm having this issue, trying to pass the value to either string_value, integer_value, or boolean_value without success. Does anyone know how to do this? Error looks like

```
Error: Invalid feature_state_value
│ 
│   with module.feature_flag.flagsmith_feature_state.feature_status,
│   on modules/feature-flag/main.tf line 25, in resource "flagsmith_feature_state" "feature_status":
│   25:   feature_state_value = {
│   26:     type         = var.ff_value_type
│   27:     string_value = var.test
│   28:   }
│ 
│ One of string_value, integer_value or boolean_value must be set
```

type         = var.ff_value_type works just fine

**Comment by dabeeeenster** [comment]
We will take a look! cc @gagantrivedi

**Comment by gagantrivedi** [comment]
@hungvodcm  are you able to share the relevant tf configuration e.g: the definition of the variable

**Comment by hungvodcm** [comment]
Use the example in the document  same error
`
resource "flagsmith_feature" "new_standard_feature" {
  feature_name = "new_standard_feature"
  project_uuid = var.fs_project_id
  description  = "This is a new standard feature"
  type         = "STANDARD"
}


resource "flagsmith_feature_state" "feature_1_dev" {
  enabled         = true
  environment_key = var.fs_env_key
  feature_id      = flagsmith_feature.new_standard_feature.id
  feature_state_value = {
    type         = var.ff_type
    string_value = "var.ff_value"
  }

}
`
variable
`
variable "ff_type" {
  type = string
  default = "unicode"
}

variable "ff_value" {
  type = string
  default = "test"
}

`
If i change string_value = "test" then it working

**Comment by gagantrivedi** [comment]
Thanks @hungvodcm I'll take a look
