### ISSUE TITLE
Flagsmith_feature_state import crash

### ISSUE THREAD

**Issue by yuhuyoyo** [Flagsmith/terraform-provider-flagsmith#81]
`terraform import flagsmith_feature_state.<my_flag_dev> <enviroment_client_key_dev>,<feature_state_uuid>`

Stack trace from the terraform-provider-flagsmith_v0.5.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1025a8a58]

goroutine 51 [running]:
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.MakeFeatureStateValueFromClientFSV(0x14000252ff8?)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/models.go:50 +0x198
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.MakeFeatureStateResourceDataFromClientFS(0x14000082960)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/models.go:108 +0x58
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureStateResource).Read(0x1400000e028, {0x102aa83c0, 0x1400054ac90}, {{{{0x102aac368, 0x140002190b0}, {0x1029c8fe0, 0x14000218e70}}, {0x102aad828, 0x140004b25a0}}, 0x1400000e080, ...}, ...)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature_state.go:233 +0x22c
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x140000a5340, {0x102aa83c0, 0x1400054ac90}, 0x1400054ad80, 0x140002535e0)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_readresource.go:97 +0x4a4
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x140000a5340, {0x102aa83c0?, 0x1400054ab40?}, 0x140000966c0)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_readresource.go:52 +0x1a4
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400009f0e0, {0x102aa83c0?, 0x1400054a180?}, 0x14000082720)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x102a78460?, 0x1400009f0e0}, {0x102aa83c0, 0x1400054a180}, 0x140000d2000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000f61e0, {0x102aac658, 0x14000480680}, 0x14000263680, 0x1400044a0c0, 0x102ef9370, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x140000f61e0, {0x102aac658, 0x14000480680}, 0x14000263680, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x290

Error: The terraform-provider-flagsmith_v0.5.0 plugin crashed!

**Comment by yuhuyoyo** [comment]
it needs to handle when feature_state_value is null: https://github.com/Flagsmith/terraform-provider-flagsmith/blob/1cf98fe95c59ba86d22d81d4daf7988fed08f9b9/flagsmith/models.go#L113

when the feature is created through ui, the feature_state_value is null. a work around is to make a noop update to make the feature_state_value an empty string, then I can import successfully.

**Comment by matthewelwell** [comment]
Thanks for this @yuhuyoyo. Would you be able to just update the description to include the exact command you're running when you get this exception?
